"""BMW hex DTC seed from research/bmw_diag_dim01_dtcs.md.

211 unique BMW 4-hex (and a few 6-hex) diagnostic trouble codes, sourced
from community/open references (BimmerFest, Bimmerforums, M5Board,
SpoolStreet, BabyBMW, BimmerProfs, AutoExplain, etc.). Short factual
titles only; the original research URL is preserved in the description
field for provenance.

Confidence ratings from the research file are NOT preserved in the seed
row — all rows are marked verified=1 (these are technical descriptions,
not opinions) and source="seed:bmw-dim01" so they are filterable.
"""
from __future__ import annotations

from pathlib import Path

from . import seed


# (code, section, title, severity, source_url)
_ROWS: list[tuple[str, str, str, str, str]] = [
    ("29CD", "misfire", "Misfire cylinder 1", "critical", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("29CE", "misfire", "Misfire cylinder 2", "critical", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("29CF", "misfire", "Misfire cylinder 3", "critical", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("29D0", "misfire", "Misfire cylinder 4", "critical", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("29D1", "misfire", "Misfire cylinder 5", "critical", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("29D2", "misfire", "Misfire cylinder 6", "critical", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("29D9", "misfire", "Misfire in case of tank filling level too low", "critical", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("29DC", "misfire", "Cylinder injection switch-off", "critical", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("29E0", "fuel", "Fuel injection rail, pressure sensor signal", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("29E1", "fuel", "Fuel pressure sensor signal", "critical", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("29E2", "fuel", "Fuel injection rail, pressure sensor signal", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("29F3", "fuel", "Fuel pressure sensor, electrical", "critical", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("29F4", "fuel", "Fuel pressure sensor", "critical", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("29F5", "fuel", "Fuel pressure control", "critical", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2AAF", "fuel", "Fuel Pump Plausibility", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2A17", "fuel", "DMTL diagnosis module tank leakage, system failure", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2A2D", "fuel", "DMTL diagnosis module tank leakage, system failure", "warn", "https://m.book118.com/html/2024/1123/8106014134007001.shtm"),
    ("2FD4", "fuel", "Fuel system (N20 related)", "warn", "https://www.babybmw.net/threads/1-series-bmw-2-0-petrol-2011-error-codes.136756/"),
    ("2A80", "vanos", "Inlet VANOS variable cam control test, input signal", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2A85", "vanos", "Outlet VANOS variable cam control test", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2A96", "vanos", "Crankshaft sensor, tooth failure", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2A9A", "vanos", "Camshaft sensor inlet, signal", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2A99", "vanos", "VANOS exhaust: control fault, camshaft stuck (community list)", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("3E80", "vanos", "Valvetronic actuator, activation: jammed mechanically", "warn", "https://wenku.csdn.net/answer/62giogaru3"),
    ("2ABC", "turbo", "Charging pressure sensor, electrical", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2ABD", "turbo", "Intake pressure sensor, re-running", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("30CF", "turbo", "Turbo/boost related", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("30FE", "turbo", "Exhaust fume turbo charger, high pressure side", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("30FF", "turbo", "Turbocharger, charge-air pressure too low (underboost)", "warn", "https://bmwtuning.co/bmw-n54-30ff-engine-fault-code-30ff-diagnosis-repair-guide/"),
    ("3100", "turbo", "Boost-pressure control, deactivation", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("28A0", "turbo", "N55 wastegate adaptation value exceeded", "warn", "https://autoexplain.com/what-is-a-turbo-wastegate/"),
    ("2D18", "turbo", "Boost control, pressure too low (N20/N26/B48/B58)", "warn", "https://autoexplain.com/what-is-a-turbo-wastegate/"),
    ("CD87", "turbo", "E-Wastegate control deviation (B48/B58)", "warn", "https://autoexplain.com/what-is-a-turbo-wastegate/"),
    ("120308", "turbo", "Charging pressure control: too low (B58)", "warn", "https://autoexplain.com/what-is-a-turbo-wastegate/"),
    ("2D2A", "turbo", "Differential pressure sensor, suction pipe: adaptation / throttle angle plausibility", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2D2E", "turbo", "Angle of throttle valve - intake pipe underpressure", "warn", "https://www.bimmerfest.com/threads/2d2e-angle-of-thottle-valve-intake-pipe-underpres.894191/"),
    ("2D29", "turbo", "MAP sensor error (intake manifold pressure)", "warn", "https://www.bimmerforums.com/forum/showthread.php?2499206-N52-rough-idle-and-MAF-fault-codes"),
    ("2AD0", "turbo", "Gear Control", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2AEC", "lambda", "NOx sensor self diagnostics", "warn", "https://bimmerprofs.com/replacing-nox-sensor-n43n53/"),
    ("2AF0", "lambda", "NOx sensor, heating", "warn", "https://bimmerprofs.com/replacing-nox-sensor-n43n53/"),
    ("2AF2", "lambda", "NOx sensor, Lambda linear", "warn", "https://bimmerprofs.com/replacing-nox-sensor-n43n53/"),
    ("2AF4", "lambda", "NOx sensor, electrical", "warn", "https://bimmerprofs.com/replacing-nox-sensor-n43n53/"),
    ("2AF6", "lambda", "NOx sensor, Lambda binary", "warn", "https://bimmerprofs.com/replacing-nox-sensor-n43n53/"),
    ("2AF9", "lambda", "NOx sensor, nox signal: coast mode check", "warn", "https://bimmerprofs.com/replacing-nox-sensor-n43n53/"),
    ("2B05", "lambda", "NOx sensor, heating (alternate)", "warn", "https://bimmerprofs.com/replacing-nox-sensor-n43n53/"),
    ("2B06", "lambda", "NOx sensor, Lambda linear (alternate)", "warn", "https://bimmerprofs.com/replacing-nox-sensor-n43n53/"),
    ("2B07", "lambda", "NOx sensor, electrical (alternate)", "warn", "https://bimmerprofs.com/replacing-nox-sensor-n43n53/"),
    ("2B09", "lambda", "NOx sensor, Lambda linear (alternate)", "warn", "https://bimmerprofs.com/replacing-nox-sensor-n43n53/"),
    ("2B0A", "lambda", "NOx sensor, Lambda binary (alternate)", "warn", "https://bimmerprofs.com/replacing-nox-sensor-n43n53/"),
    ("2AFB", "lambda", "NOx sensor, Lambda binary (alternate)", "warn", "https://bimmerprofs.com/replacing-nox-sensor-n43n53/"),
    ("2B0B", "lambda", "NOx sensor, Lambda binary (alternate)", "warn", "https://bimmerprofs.com/replacing-nox-sensor-n43n53/"),
    ("2EAE", "lambda", "NOx sensor message missing (timeout)", "warn", "https://bimmerprofs.com/replacing-nox-sensor-n43n53/"),
    ("30D6", "lambda", "NOx sensor, plausibility", "warn", "https://bimmerprofs.com/replacing-nox-sensor-n43n53/"),
    ("30D8", "lambda", "NOx sensor, sensor damaged", "warn", "https://bimmerprofs.com/replacing-nox-sensor-n43n53/"),
    ("30DA", "lambda", "NOx sensor, heating time", "warn", "https://bimmerprofs.com/replacing-nox-sensor-n43n53/"),
    ("30DC", "lambda", "NOx sensor, heating", "warn", "https://bimmerprofs.com/replacing-nox-sensor-n43n53/"),
    ("30DE", "lambda", "NOx sensor - Lambdaprobe before catalyst, correlation", "warn", "https://bimmerprofs.com/replacing-nox-sensor-n43n53/"),
    ("30E0", "lambda", "NOx sensor, offset", "warn", "https://bimmerprofs.com/replacing-nox-sensor-n43n53/"),
    ("30E2", "lambda", "NOx sensor, thrust test", "warn", "https://bimmerprofs.com/replacing-nox-sensor-n43n53/"),
    ("30E4", "lambda", "NOx sensor, aging", "warn", "https://bimmerprofs.com/replacing-nox-sensor-n43n53/"),
    ("30E6", "lambda", "NOx sensor, dynamics", "warn", "https://bimmerprofs.com/replacing-nox-sensor-n43n53/"),
    ("30E9", "lambda", "Nitric oxide catalytic converter, aging", "warn", "https://bimmerprofs.com/replacing-nox-sensor-n43n53/"),
    ("30EA", "lambda", "DeNox catalytic converter sulfurized", "warn", "https://bimmerprofs.com/replacing-nox-sensor-n43n53/"),
    ("2D1C", "throttle", "Accelerator pedal module, pedal sensor signal 2", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2D58", "throttle", "DME digital motor electronics, internal failure: control nominal torque", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2D5A", "throttle", "Control motor torque limitation", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2F8F", "throttle", "Throttle/pedal related", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2D25", "throttle", "Mass Air Flow Excessive - External Tuning Box Detected", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2710", "throttle", "Throttle valve, function: jammed permanently", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("2711", "throttle", "Throttle valve, function: jammed briefly", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("2714", "throttle", "Throttle valve, function: sluggish, too slow", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("27E4", "throttle", "Accelerator-pedal module, pedal-travel sensor multiple fault", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("27E8", "throttle", "Accelerator pedal module, synchronisation error between signal 1 and 2", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("27D9", "throttle", "Accelerator pedal module, pedal sensor 1, short circuit to B+", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("27DA", "throttle", "Accelerator pedal module, pedal sensor 1, short circuit to earth", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("27DB", "throttle", "Pedal module, pedal sensor 2, short circuit to B+", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("27DC", "throttle", "Pedal module, pedal sensor 2, short circuit to earth", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("28A1", "throttle", "Throttle-valve angle - intake-manifold pressure, correlation: limit value not exceeded", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("28A4", "throttle", "Throttle valve, throttle valve potentiometer 1, short to B+ or open circuit", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("28A5", "throttle", "Throttle valve, throttle valve potentiometer 1, short circuit to earth", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("28A8", "throttle", "Throttle valve, throttle potentiometer 2, short circuit to B+", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("28A9", "throttle", "Throttle valve, throttle potentiometer 2, short circuit to earth", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("28B0", "throttle", "Throttle valve: Limp-home operating mode active", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("28B4", "throttle", "Throttle valve, throttle potentiometer: plausibility timing fault between potentiometer 1 and 2", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("28B8", "throttle", "DME, internal fault, activation of throttle valve: short circuit", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("28B9", "throttle", "DME, internal fault, activation of throttle valve: excess temperature or current too high", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("28BA", "throttle", "DME, internal fault, activation of throttle valve: internal communication fault", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("28BB", "throttle", "DME, internal fault, activation of throttle valve: line disconnection", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("28BC", "throttle", "Throttle valve actuator, closing spring test: cancellation of check", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("28BD", "throttle", "Throttle valve actuator, closing spring test: fault during spring check", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("28C0", "throttle", "Throttle valve actuator, opening spring test: cancellation of check", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("28C1", "throttle", "Throttle valve actuator, opening spring test: fault during spring check", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("28C4", "throttle", "Throttle valve, adaptation: emergency running position not adapted", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("28CC", "throttle", "Throttle valve, adaptation: marginal conditions not met", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("28CD", "throttle", "Throttle valve, adaptation: marginal conditions not met; battery voltage too low", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("28D0", "throttle", "Throttle valve, adaptation: initial adaptation, lower limit position not taught in", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("28D4", "throttle", "Throttle valve, adaptation: teach in again, lower limit position not taught in", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("2906", "throttle", "Intake air system: suspicion of leaks between turbocharger and intake valves", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("2E84", "cooling", "Cooling system related", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2EE0", "cooling", "Cooling system related", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2EE1", "cooling", "Cooling system related", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2EE2", "cooling", "Cooling system related", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2EE3", "cooling", "Cooling system related", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2F0D", "cooling", "Cooling system related", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2E83", "cooling", "Electric coolant pump: communication fault", "warn", "https://www.bimmerfest.com/threads/water-pump-problems.1454350/"),
    ("2E85", "cooling", "Electric coolant pump: communication / cutoff", "warn", "https://www.bimmerfest.com/threads/water-pump-problems.1454350/"),
    ("2E8D", "cooling", "Cooling system (from community PDF)", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("279B", "cooling", "Map cooling thermostat mechanically stuck (also 2EF4)", "warn", "https://www.bimmerfest.com/threads/code-279b-dme-thermostat-stuck.1413711/"),
    ("2EF4", "cooling", "Map cooling thermostat mechanically stuck (same as 279B)", "warn", "https://www.bimmerfest.com/threads/code-279b-dme-thermostat-stuck.1413711/"),
    ("2774", "sensor", "Mass air flow sensor, plausibility: air mass compared with model too high", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("2775", "sensor", "Mass air flow sensor, plausibility: air mass compared with model too low", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("2778", "sensor", "Air mass sensor, signal: implausible period duration, loose contact low frequency", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("2779", "sensor", "Air mass sensor, signal: implausible period duration, loose contact high frequency", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("277A", "sensor", "Air mass sensor, signal: short-circuit or line break (open circuit)", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("280E", "sensor", "Absolute pressure sensor, intake manifold, plausibility: intake-manifold pressure too high", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("280F", "sensor", "Absolute pressure sensor, intake manifold, plausibility: intake-manifold pressure too low", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("281A", "sensor", "Absolute pressure sensor, intake pipe, electrical: short circuit to B+", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("281B", "sensor", "Absolute pressure sensor, intake pipe, electrical: short circuit to earth", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("283C", "sensor", "Ambient pressure sensor, electrical: short to B+ or open circuit", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("283D", "sensor", "Ambient pressure sensor, electrical: short circuit to earth", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("2841", "sensor", "Ambient pressure sensor, overrun: pressure too high", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("2842", "sensor", "Ambient pressure sensor, overrun: pressure too low", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("284C", "sensor", "Ambient pressure sensor, plausibility: pressure too high", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("284D", "sensor", "Ambient pressure sensor, plausibility: pressure too low", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("284E", "sensor", "Ambient pressure sensor, plausibility: pressure implausible", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("284F", "sensor", "Ambient pressure sensor, plausibility: pressure implausible", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("2793", "battery", "DME: Power management, battery", "warn", "https://www.m5board.com/threads/error-codes-help-me-bring-my-e60-back-from-the-dead.604828/"),
    ("3886", "battery", "System voltage: voltage too high", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("5088", "transmission", "Sensors gear selector switch", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("51A6", "transmission", "Transmission related", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("5101", "transmission", "SMG III: Analyze hydraulic sensor", "warn", "https://www.m5board.com/threads/m5-m6-s85-recall-tech-service-bulletin-service-information-bulletin-technical-docs-thread-one-stop-shop.213154/"),
    ("4F82", "transmission", "Transmission error (EGS/GWS)", "warn", "https://www.bimmerforums.com/forum/showthread.php?2324654-2-transmission-error-code"),
    ("507B", "transmission", "Parking brake failure (transmission related)", "warn", "https://www.bimmerforums.com/forum/showthread.php?2324654-2-transmission-error-code"),
    ("CDA7", "transmission", "Transmission: status gear reverse", "warn", "https://5series.net/forums/e60-discussion-2/identification-two-inpa-errors-141133/"),
    ("4FA0", "transmission", "SMG: clutch (activation position deviation)", "warn", "https://www.m5board.com/threads/error-codes-help-me-bring-my-e60-back-from-the-dead.604828/"),
    ("5401", "transmission", "SMG: starter enable", "warn", "https://www.m5board.com/threads/error-codes-help-me-bring-my-e60-back-from-the-dead.604828/"),
    ("520A", "transmission", "SMG: signal, steering angle is faulty (DSC)", "warn", "https://www.m5board.com/threads/error-codes-help-me-bring-my-e60-back-from-the-dead.604828/"),
    ("CF33", "transmission", "Transmission code (from community PDF)", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("6140", "transmission", "Transmission code (from community PDF)", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("5DE0", "dsc", "DSC-ECU: ECU-internal plausibility VASP-U_Bit", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("5DE1", "dsc", "DSC-ECU: ECU-internal clockstatus missing clock", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("5E1A", "dsc", "DSC-ECU: SPI transmission failure multi IC", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("5E40", "dsc", "Wheel speed sensor rear right: signal edge missing", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("5E5B", "dsc", "Stability control - wheel speed sensor general long-term error", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("51B0", "dsc", "DSC signal not plausible: brake pressure signal", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("5E19", "dsc", "DSC: engine management interface", "warn", "https://www.m5board.com/threads/error-codes-help-me-bring-my-e60-back-from-the-dead.604828/"),
    ("A092", "body", "SHD Standardization", "info", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("A0B0", "body", "ECU input brake lights", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("A0B4", "body", "Fault engine start starter", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("A375", "body", "Communication with airbag ECU disturbed", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("A3AD", "body", "CAN ID 1D0 error: Engine data", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("A3AE", "body", "CAN ID 0AA error: Idle engine speed", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("A554", "body", "Alive telephone", "info", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("A559", "body", "Clamp 30g_f cutoff", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("A8B6", "body", "Error will not cause a warning light", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("A10A", "body", "Body module code (from community PDF)", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("A127", "body", "Body module code (from community PDF)", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("A114", "body", "CAS: line fault, electrical steering lock", "warn", "https://www.m5board.com/threads/error-codes-help-me-bring-my-e60-back-from-the-dead.604828/"),
    ("A118", "body", "CAS: roadstead signal implausible", "warn", "https://www.m5board.com/threads/error-codes-help-me-bring-my-e60-back-from-the-dead.604828/"),
    ("A0B2", "body", "CAS: supply, terminal 30E/30L", "warn", "https://www.m5board.com/threads/error-codes-help-me-bring-my-e60-back-from-the-dead.604828/"),
    ("2F44", "body", "EWS preventing manipulation (immobilizer)", "warn", "https://bbs.autel.com/autelsupport/Diagnostics/27585.jhtml"),
    ("2F45", "body", "EWS preventing manipulation (related to 2F44)", "warn", "https://www.bimmerfest.com/threads/help-bmw-no-crank-no-start-codes-2f44ews-2f45ews-dme-a0b2-whats-needs-to-be-done-to-fix-this-issue.1448260/"),
    ("D354", "can", "PT-CAN: Message TORQUE_1 (ID 0xA8) not received or wrong message length", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("D355", "can", "PT-CAN: Message TORQUE_2 (ID 0x0A9) not received or wrong message length", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("D356", "can", "PT-CAN: Message TORQUE_3 (ID 0xAA) not received or wrong message length", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("D904", "can", "K CAN wire error", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("E717", "can", "CAN message: Dates of engine", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("E71A", "can", "CAN message: Torque 3", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("E18C", "can", "CAN related (from community PDF)", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("E18F", "can", "CAN related (from community PDF)", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("3BD6", "can", "PT-CAN message vehicle speed checksum wrong/alive check", "info", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("3BD7", "can", "PT-CAN no message vehicle speed", "info", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("3BD8", "can", "PT-CAN no message transmission data 2", "info", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("3BD9", "can", "PT-CAN message DKG status missing", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("3BDA", "can", "PT-CAN message transmission data 3 checksum wrong", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("3BDB", "can", "PT-CAN no message transmission data 3", "info", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("3BDC", "can", "PT-CAN message ETC torque request checksum wrong", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("3BDD", "can", "PT-CAN no message ETC torque request", "info", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("3BDE", "can", "PT-CAN message twin-clutch gearbox torque request checksum wrong", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("3BDF", "can", "PT-CAN no message twin-clutch gearbox torque request", "info", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("3BE0", "can", "PT-CAN message gearbox data checksum wrong", "warn", "https://spoolstreet.com/threads/n55-codes-list.580/"),
    ("9C54", "hvac", "AUC sensor (automatic recirculation control)", "warn", "https://5series.net/forums/e60-discussion-2/identification-two-inpa-errors-141133/"),
    ("A6CF", "hvac", "AUC sensor (IHKA)", "warn", "https://www.bimmerfest.com/threads/ihka-fault-codes.1290835/"),
    ("E72B", "hvac", "No message (solar sensor, 0x3D3), receiver IHKA", "info", "https://www.bimmerfest.com/threads/ihka-fault-codes.1290835/"),
    ("E723", "hvac", "No message (condensation sensor, 0x2D1), receiver IHKA", "info", "https://www.bimmerfest.com/threads/ihka-fault-codes.1290835/"),
    ("E729", "hvac", "No message (automatic air recirculation control sensor, 0x2D0), receiver JBE", "info", "https://www.bimmerfest.com/threads/ihka-fault-codes.1290835/"),
    ("9C70", "hvac", "ISupply, SZM (IHKA climate control)", "warn", "https://www.bimmerfest.com/threads/climate-control-system-ihka-fault.1310281/"),
    ("9C59", "hvac", "Evaporator temperature sensor (IHKA)", "warn", "https://www.bimmerfest.com/threads/climate-control-system-ihka-fault.1310281/"),
    ("9C5A", "hvac", "Heating heat-exchanger sensor, left (IHKA)", "warn", "https://www.bimmerfest.com/threads/climate-control-system-ihka-fault.1310281/"),
    ("9C5C", "hvac", "Heating heat-exchanger sensor, right (IHKA)", "warn", "https://www.bimmerfest.com/threads/climate-control-system-ihka-fault.1310281/"),
    ("9C60", "hvac", "SZM button 1 (IHKA)", "warn", "https://www.bimmerfest.com/threads/climate-control-system-ihka-fault.1310281/"),
    ("9C61", "hvac", "SZM button 2 (IHKA)", "warn", "https://www.bimmerfest.com/threads/climate-control-system-ihka-fault.1310281/"),
    ("9C62", "hvac", "SZM button 3 (IHKA)", "warn", "https://www.bimmerfest.com/threads/climate-control-system-ihka-fault.1310281/"),
    ("9C63", "hvac", "SZM button 4 (IHKA)", "warn", "https://www.bimmerfest.com/threads/climate-control-system-ihka-fault.1310281/"),
    ("9C65", "hvac", "SZM variant coding 2 (IHKA)", "warn", "https://www.bimmerfest.com/threads/climate-control-system-ihka-fault.1310281/"),
    ("B1000", "airbag", "Airbag ECU malfunction (SRS module internal failure)", "warn", "https://www.go-parts.com/garage/obd-b1000-bmw-3-series-2005-2013"),
    ("93AE", "airbag", "ACSM/MRS: side airbag driver, rear", "warn", "https://www.m5board.com/threads/error-codes-help-me-bring-my-e60-back-from-the-dead.604828/"),
    ("93D2", "airbag", "ACSM/MRS: telltale lamp for front passenger airbag deactivation", "warn", "https://www.m5board.com/threads/error-codes-help-me-bring-my-e60-back-from-the-dead.604828/"),
    ("93C3", "airbag", "ACSM/MRS: seat-occupancy detector, passenger", "warn", "https://www.m5board.com/threads/error-codes-help-me-bring-my-e60-back-from-the-dead.604828/"),
    ("9408", "airbag", "ACSM/MRS: under voltage during test", "warn", "https://www.m5board.com/threads/error-codes-help-me-bring-my-e60-back-from-the-dead.604828/"),
    ("2F4A", "other", "Engine code (from community PDF)", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2F4C", "other", "Engine code (from community PDF)", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2F6C", "other", "Engine code (from community PDF)", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2F9E", "other", "Engine code (from community PDF)", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2FBE", "other", "Engine code (from community PDF)", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2DC3", "other", "Engine code (from community PDF)", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2DC5", "other", "Engine code (from community PDF)", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2DEC", "other", "Engine code (from community PDF)", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("2DED", "other", "Engine code (from community PDF)", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("30F1", "other", "Engine code (from community PDF)", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
    ("30F2", "other", "Engine code (from community PDF)", "warn", "https://www.bimmerfest.com/threads/error-code-2a82-and-2a99.604589/"),
]


def _rows() -> list[dict]:
    return [
        {
            "code": code,
            "category": "bmw-specific",
            "title": title,
            "description": f"Source: {url}",
            "likely_causes": None,
            "severity": severity,
            "source": "seed:bmw-dim01",
            "verified": 1,
        }
        for code, section, title, severity, url in _ROWS
    ]


def run(db_path: Path) -> None:
    """Idempotent. Seeds all 211 BMW dim01-research codes."""
    seed.seed_many(db_path, _rows())


seed.register_source(run)
