"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const { manualUrl } = require("../service_manual.js");
test("known prefix", ()=>{ assert.ok(manualUrl("2A82").includes("2A82")); assert.ok(manualUrl("2a82").includes("vanos-inlet")); });
test("fuel rail family", ()=>{ assert.ok(manualUrl("29E0").includes("fuel-rail")); assert.ok(manualUrl("29E1").includes("fuel-rail")); });
test("sae mapped", ()=>{ assert.ok(manualUrl("P0171").includes("fuel-trim-lean")); });
test("fallback search", ()=>{ assert.ok(manualUrl("P9999").includes("search?q=P9999")); });
test("invalid returns null", ()=>{ assert.equal(manualUrl(""), null); assert.equal(manualUrl("ZZZ"), null); });
test("4-6 hex", ()=>{ assert.ok(manualUrl("30FF")); assert.equal(manualUrl("123"), null); });
test("vanos timing sae", ()=>{ assert.ok(manualUrl("P0011").includes("vanos-timing")); });
test("frm lighting", ()=>{ assert.ok(manualUrl("9CC1").includes("frm/lighting")); });
